telephony/urls.py
from django.urls import path
from .views import (
  ServiceProviderListView, ServiceProviderCreateView, ServiceProviderUpdateView, ServiceProviderDetailView, ServiceProviderDeleteView,
  ServiceProviderRepListView, ServiceProviderRepCreateView, ServiceProviderRepUpdateView, ServiceProviderRepDetailView, ServiceProviderRepDeleteView,
  LocationListView, LocationCreateView, LocationUpdateView, LocationDetailView, LocationDeleteView, ValidateLocationView,
  LocationFunctionListView, LocationFunctionCreateView, LocationFunctionUpdateView, LocationFunctionDeleteView,
  PhoneNumberListView, PhoneNumberCreateView, PhoneNumberUpdateView, PhoneNumberDetailView, PhoneNumberDeleteView, PhoneNumberBulkUpdateView,
  PhoneNumberRangeListView, PhoneNumberRangeCreateView, PhoneNumberRangeUpdateView, PhoneNumberRangeDetailView, PhoneNumberRangeDeleteView,
  UsageTypeListView, UsageTypeCreateView, UsageTypeUpdateView, UsageTypeDetailView, UsageTypeDeleteView,
  CircuitListView, CircuitCreateView, CircuitUpdateView, CircuitDetailView, CircuitDeleteView,
  SwitchTypeListView, SwitchTypeCreateView, SwitchTypeUpdateView, SwitchTypeDetailView, SwitchTypeDeleteView,
  ConnectionTypeListView, ConnectionTypeCreateView, ConnectionTypeUpdateView, ConnectionTypeDetailView, ConnectionTypeDeleteView,
  country_list,
  generic_bulk_update, generic_bulk_delete
)
from .models import Location, ServiceProvider, CircuitDetail, PhoneNumber, PhoneNumberRange, Country, LocationFunction, ServiceProviderRep

app_name = 'telephony'

urlpatterns = [
      # Country-related URLs
    path('country_list/', country_list, name='country_list'),
    path('countries/', country_list, name='country_list'),
  
    # Location-related URLs
    path('location/', LocationListView.as_view(), name='location'),
    path('location/new/', LocationCreateView.as_view(), name='location_new'),
    path('location/<int:pk>/edit/', LocationUpdateView.as_view(), name='location_edit'),
    path('location/<int:pk>/details/', LocationDetailView.as_view(), name='location_details'),
    path('location/<int:pk>/delete/', LocationDeleteView.as_view(), name='location_delete'),
    path('location/<int:pk>/validate/', ValidateLocationView.as_view(), name='validate_location'),
    path('location/batch_edit/', generic_bulk_update, {'model_class': Location}, name='location_batch_edit'),
    path('location/batch_delete/', generic_bulk_delete, {'model_class': Location}, name='location_batch_delete'),

    #Location-Function/Purpose URLs
    path('location_function/', LocationFunctionListView.as_view(), name='location_function'),
    path('location_function/new/', LocationFunctionCreateView.as_view(), name='location_function_new'),
    path('location_function/<int:pk>/edit/', LocationFunctionUpdateView.as_view(), name='location_function_edit'),
    path('location_function/<int:pk>/delete/', LocationFunctionDeleteView.as_view(), name='location_function_delete'),
    
    # Service provider-related URLs
    path('service_provider/', ServiceProviderListView.as_view(), name='service_provider'),
    path('service_provider/new/', ServiceProviderCreateView.as_view(), name='service_provider_new'),
    path('service_provider/<int:pk>/edit/', ServiceProviderUpdateView.as_view(), name='service_provider_edit'),
    path('service_provider/<int:pk>/details/', ServiceProviderDetailView.as_view(), name='service_provider_get'),
    path('service_provider/<int:pk>/delete/', ServiceProviderDeleteView.as_view(), name='service_provider_delete'),
    
    # Service provider rep-related URLs
    path('service_provider_rep/', ServiceProviderRepListView.as_view(), name='service_provider_rep'),
    path('service_provider_rep/new/', ServiceProviderRepCreateView.as_view(), name='service_provider_rep_new'),
    path('service_provider_rep/<int:pk>/edit', ServiceProviderRepUpdateView.as_view(), name='service_provider_rep_edit'),
    path('service_provider_rep/<int:pk>/delete/', ServiceProviderRepDeleteView.as_view(), name='service_provider_rep_delete'),
   
    # Phone number-related URLs
    path('phone_number/', PhoneNumberListView.as_view(), name='phone_number'),
    path('phone_number/new/', PhoneNumberCreateView.as_view(), name='phone_number_new'),
    path('phone_number/<int:pk>/edit/', PhoneNumberUpdateView.as_view(), name='phone_number_edit'),
    path('phone_number/<int:pk>/details/', PhoneNumberDetailView.as_view(), name='phone_number_details'),
    path('phone_number/<int:pk>/delete/', PhoneNumberDeleteView.as_view(), name='phone_number_delete'),
    path('phone_number/batch_edit/', generic_bulk_update, {'model_class': PhoneNumber}, name='phone_number_batch_edit'),
    path('phone_number/batch_delete/', generic_bulk_delete, {'model_class': PhoneNumber}, name='phone_number_batch_delete'),
    path('phone_number_bulk_update/', PhoneNumberBulkUpdateView.as_view(), name='phone_number_bulk_update'),

    # Phone Number Range-related URLs
    path('phone_number_range/', PhoneNumberRangeListView.as_view(), name='phone_number_range'),
    path('phone_number_range/new/', PhoneNumberRangeCreateView.as_view(), name='phone_number_range_new'),
    path('phone_number_range/<int:pk>/edit/', PhoneNumberRangeUpdateView.as_view(), name='phone_number_range_edit'),
    path('phone_number_range/<int:pk>/details/', PhoneNumberRangeDetailView.as_view(), name='phone_number_range_details'),
    path('phone_number_range/<int:pk>/delete/', PhoneNumberRangeDeleteView.as_view(), name='phone_number_range_delete'),
    
   #Usage Type URLs
    path('usage_type/', UsageTypeListView.as_view(), name='usage_type'),
    path('usage_type/new/', UsageTypeCreateView.as_view(), name='usage_type_new'),
    path('usage_type/<int:pk>/edit/', UsageTypeUpdateView.as_view(), name='usage_type_edit'),
    path('usage_type/<int:pk>/details/', UsageTypeDetailView.as_view(), name='usage_type_details'),
    path('usage_type/<int:pk>/delete/', UsageTypeDeleteView.as_view(), name='usage_type_delete'),

    #Circuits URLs
    path('circuit_detail/', CircuitListView.as_view(), name='circuit_detail'),
    path('circuit_detail/new/', CircuitCreateView.as_view(), name='circuit_detail_new'),
    path('circuit_detail/<int:pk>/edit/', CircuitUpdateView.as_view(), name='circuit_detail_edit'),
    path('circuit_detail/<int:pk>/details/', CircuitDetailView.as_view(), name='circuit_detail_details'),
    path('circuit_detail/<int:pk>/delete/', CircuitDeleteView.as_view(), name='circuit_detail_delete'),

   #Switch Type URLs
    path('switch_type/', SwitchTypeListView.as_view(), name='switch_type'),
    path('switch_type/new/', SwitchTypeCreateView.as_view(), name='switch_type_new'),
    path('switch_type/<int:pk>/edit/', SwitchTypeUpdateView.as_view(), name='switch_type_edit'),
    path('switch_type/<int:pk>/details/', SwitchTypeDetailView.as_view(), name='switch_type_details'),
    path('switch_type/<int:pk>/delete/', SwitchTypeDeleteView.as_view(), name='switch_type_delete'),

   #Connection Type URLs
    path('connection_type/', ConnectionTypeListView.as_view(), name='connection_type'),
    path('connection_type/new/', ConnectionTypeCreateView.as_view(), name='connection_type_new'),
    path('connection_type/<int:pk>/edit/', ConnectionTypeUpdateView.as_view(), name='connection_type_edit'),
    path('connection_type/<int:pk>/details/', ConnectionTypeDetailView.as_view(), name='connection_type_details'),
    path('connection_type/<int:pk>/delete/', ConnectionTypeDeleteView.as_view(), name='connection_type_delete'),

]

telephony_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from telephony import views as telephony_views
from uc_data_import import views as uc_data_import_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", telephony_views.index, name="index"),
    path('telephony/', include('telephony.urls', namespace='telephony')),
    path('uc_data_import/', include('uc_data_import.urls', namespace='uc_data_import')),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

telephony/templates/telephony/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLinkView" role="button" data-bs-toggle="dropdown" aria-expanded="false">Company</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLinkView">
            <li>
              <hr class="dropdown-divider"">Administration
            </li>
            <li><a class="dropdown-item" href="{% url 'telephony:location' %}">Locations</a></li>
            <li><a class="dropdown-item" href="{% url 'telephony:phone_number' %}">Phone Numbers</a></li>
            <li><a class="dropdown-item" href="{% url 'telephony:phone_number_range' %}">Phone Number Ranges</a></li>
            <li><hr class="dropdown-divider">Resources</li>
            <li><a class="dropdown-item" href="{% url 'telephony:country_list' %}">Countries</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLinkManage" role="button" data-bs-toggle="dropdown" aria-expanded="false">Leased Services</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLinkManage">
            <li><hr class="dropdown-divider">Administration</li>
            <li><a class="dropdown-item" href="{% url 'telephony:service_provider' %}">Service Providers</a></li>
            <li><a class="dropdown-item" href="{% url 'telephony:service_provider_rep' %}">Service Provider Reps</a></li>
            <li><a class="dropdown-item" href="{% url 'telephony:phone_number' %}">Phone Numbers</a></li>
            <li><a class="dropdown-item" href="{% url 'telephony:phone_number_range' %}">Phone Number Ranges</a></li>
            <li><a class="dropdown-item" href="{% url 'telephony:circuit_detail' %}">Circuits</a></li>
            <li><a class="dropdown-item" href="{% url 'telephony:switch_type' %}">Switch Type</a></li>
            <li><a class="dropdown-item" href="{% url 'telephony:connection_type' %}">Connection Type</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLinkManage" role="button" data-bs-toggle="dropdown"
            aria-expanded="false">Asset Tracking</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLinkManage">
            <li>
              <hr class="dropdown-divider">Phones
            </li>
            <li><a class="dropdown-item" href="{% url 'telephony:service_provider' %}">Phones</a></li>
            <li><a class="dropdown-item" href="{% url 'telephony:location' %}">Gateways</a></li>
            <li><a class="dropdown-item" href="{% url 'telephony:phone_number' %}">Analog Gateways</a></li>
            <li><a class="dropdown-item" href="{% url 'telephony:phone_number_range' %}">Phone Number Ranges</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLinkManage" role="button" data-bs-toggle="dropdown"
            aria-expanded="false">Custom Settings</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLinkManage">
            <li>
              <hr class="dropdown-divider">Customize
            </li>
            <li><a class="dropdown-item" href="{% url 'telephony:usage_type' %}">Use Type</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLinkResources" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">Resources</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLinkResources">
            <li><a class="dropdown-item" href="{% url 'telephony:country_list' %}">Countries</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

telephony/templates/telephony/_navbar_original.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLinkView" role="button" data-bs-toggle="dropdown" aria-expanded="false">View</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLinkView">
            <li>
              <hr class="dropdown-divider"">Administration
            </li>
            <!-- <li><a class="dropdown-item" href="{% url 'telephony:locations' %}">Locations</a></li> -->
            <!-- <li><a class="dropdown-item" href="{% url 'telephony:phone_numbers' %}">Phone Numbers</a></li> -->
            <li><a class="dropdown-item" href="{% url 'telephony:service_provider' %}">Service Providers</a></li>
            <!-- <li><a class="dropdown-item" href="{% url 'telephony:circuits' %}">Circuits</a></li> -->
            <li><hr class="dropdown-divider">Resources</li>
            <li><a class="dropdown-item" href="{% url 'telephony:country_list' %}">Countries</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLinkManage" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">Manage</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLinkManage">
            <li><hr class="dropdown-divider">Administration</li>
            <!-- <li><a class="dropdown-item" href="{% url 'telephony:locations' %}">Locations</a></li> -->
            <!-- <li><a class="dropdown-item" href="{% url 'telephony:phone_numbers' %}">Phone Numbers</a></li> -->
            <li><a class="dropdown-item" href="{% url 'telephony:service_provider' %}">Service Providers</a></li>
            <!-- <li><a class="dropdown-item" href="{% url 'telephony:circuits' %}">Circuits</a></li> -->
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLinkResources" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">Resources</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLinkResources">
            <li><a class="dropdown-item" href="{% url 'telephony:country_list' %}">Countries</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

telephony/templates/telephony/circuit_detail.html
{% extends 'telephony/base.html' %}
{% load custom_filters %}

{% block content %}
  <h1>Add Circuits</h1>
{% endblock %}

{% block form_content %}
<div>
  <div class="row">
    <div class="col-md-4">
      <div>
        <label for="id_circuit_number" class="form-label">Circuit Number:
          {% info_icon "Point of contact when you need someone at the facility." %}
        </label>
        {{ form.circuit_number|add_class:"form-control" }}
      </div>
      <div>
        <label for="id_provider" class="form-label">Provider:
          {% info_icon "Point of contact when you need someone at the facility." %}
        </label>
        {{ form.provider|add_class:"form-control" }}
      </div>
      <div>
        <label for="id_location" class="form-label">Location Contact:
          {% info_icon "Point of contact when you need someone at the facility." %}
        </label>
        {{ form.location|add_class:"form-control" }}
      </div>
      <div>
        <label for="id_btn" class="form-label">BTN:
          {% info_icon "Point of contact when you need someone at the facility." %}
        </label>
        {{ form.btn|add_class:"form-control" }}
      </div>
      <div>
        <label for="id_supported_codecs" class="form-label">Supported Codecs:
          {% info_icon "Point of contact when you need someone at the facility." %}
        </label>
        {{ form.supported_codecs|add_class:"form-control" }}
      </div>
      <div>
        <label for="id_bandwidth" class="form-label">Bandwidth:
          {% info_icon "Point of contact when you need someone at the facility." %}
        </label>
        {{ form.bandwidth|add_class:"form-control" }}
      </div>
    </div>
    <div class="col-md-4">
      <div>
        <label for="id_voice_channel_count" class="form-label">Voice Channel Count:
          {% info_icon "Point of contact when you need someone at the facility." %}
        </label>
        {{ form.voice_channel_count|add_class:"form-control" }}
      </div>
      <div>
        <label for="id_connection_type" class="form-label">Connection Type:
          {% info_icon "Point of contact when you need someone at the facility." %}
        </label>
        {{ form.connection_type|add_class:"form-control" }}
      </div>
      <div>
        <label for="id_ipv4_address" class="form-label">IPv4 Address:
          {% info_icon "Point of contact when you need someone at the facility." %}
        </label>
        {{ form.ipv4_address|add_class:"form-control" }}
      </div>
      <div>
        <label for="id_ipv6_address" class="form-label">IPv6 Address:
          {% info_icon "Point of contact when you need someone at the facility." %}
        </label>
        {{ form.ipv6_address|add_class:"form-control" }}
      </div>
    </div>
    <div class="col-md-4">
      <div>
        <label for="id_contract_details" class="form-label">Contract Details:</label>
        {{ form.contract_details|add_class:"form-control" }}
      </div>
      <div>
        <label for="id_notes" class="form-label">Notes:</label>
        {{ form.notes|add_class:"form-control" }}
      </div>
    </div>
  </div>
</div>
{% endblock %}

telephony/templates/telephony/connection_type.html
{% extends 'telephony/base.html' %}
{% load custom_filters %}

{% block content %}
  <h1>Add Connection Type</h1>
{% endblock %}

telephony/templates/telephony/country_list.html
<!-- telephony/templates/telephony/country_list.html -->

{% extends 'telephony/base.html' %}

{% block content %}
<h2>Countries</h2>
<table id="country_table" class="table table-hover">
  <thead>
    <tr style="text-align: center; vertical-align: middle;">
      <th>Common Name</th>
      <th>ISO2</th>
      <th>ISO3</th>
      <th>E164 Code</th>
      <th>Region</th>
      <th>Subregion</th>
      <th>Capital</th>
    </tr>
  </thead>
  <tbody>
    {% for country in countries %}
    <tr>
      <td>{{ country.name }}</td>
      <td style="text-align:center">{{ country.iso2_code }}</td>
      <td style="text-align:center">{{ country.iso3_code }}</td>
      <td style="text-align:center">{{ country.e164_code }}</td>
      <td>{{ country.region }}</td>
      <td>{{ country.subregion }}</td>
      <td>{{ country.capital }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

{% block extra_js %}


<script>
  $(document).ready(function () {
    $('#country_table').DataTable({
      "paging": true,
      "searching": true,
      "ordering": true,
      "info": true,
      "lengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
      "pageLength": -1
    });
  });
</script>
{% endblock %}

telephony/templates/telephony/index.html
{% extends 'telephony/base.html' %}

{% block content %}
<h2>Welcome to Telephony Tracker</h2>
<p>Effortlessly track your telephony environment.</p>
{% endblock %}

telephony/templates/telephony/location.html
{% extends "telephony/base.html" %}
{% load custom_filters %}

{% block content %}
<h2>Locations</h2>
{% endblock %}

{% block form_content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3">
      <label for="id_site_id" class="form-label">Site ID:
        {% info_icon "A system generated unique value that is assigned based on a location's physical characteristics." %}
      </label>
      <input type="text" id="id_site_id" name="site_id" class="form-control" value="{{ form.instance.site_id }}" readonly>
    </div>
    <div class="col-md-3">
      <label for="id_name" class="form-label">Name:
        {% info_icon "Name of the facility as system administrators are familiar with." %}
      </label>
      {{ form.display_name|add_class:"form-control" }}
    </div>
    <div class="col-md-3">
      <label for="id_house_number" class="form-label">*House Number:
        {% info_icon "The numeric portion of the physical locations address." %}
      </label>
      {{ form.house_number|add_class:"form-control" }}
    </div>
    <div class="col-md-3">
      <label for="id_road" class="form-label">*Road:
        {% info_icon "The name of the road/street this location is at according to the local postal service." %}
      </label>
      {{ form.road|add_class:"form-control" }}
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <label for="id_city" class="form-label">*City:
        {% info_icon "The name of the City this location is at according to the local postal service." %}
      </label>
      {{ form.city|add_class:"form-control" }}
    </div>
    <div class="col-md-3">
      <label for="id_state" class="form-label">*State:
        {% info_icon "Name or Abbreviation of the State this physical site is located within." %}
      </label>
      {{ form.state|add_class:"form-control" }}
    </div>
    <div class="col-md-3">
      <label for="id_country" class="form-label">*Country:
        {% info_icon "Select the Country from the list where this facility is physically located." %}
      </label>
      {{ form.country|add_class:"form-control" }}
    </div>
    <div class="col-md-3">
      <label for="id_postcode" class="form-label">*Postcode:
        {% info_icon "The Post Code/Zip Code for this physical location according to the local postal service." %}
      </label>
      {{ form.postcode|add_class:"form-control" }}
    </div>
  </div>
  <div class="row">
    <div class="col-md-9">
      <div class="row">
        <div class="col-md-4">
          <div>
            <label for="id_contact_person" class="form-label">Location Contact:
              {% info_icon "Point of contact when you need someone at the facility." %}
            </label>
            {{ form.contact_person|add_class:"form-control" }}
          </div>
          <div>
            <label for="id_contact_email" class="form-label">Contact Email:
              {% info_icon "Email address for the locations contact person." %}
            </label>
            {{ form.contact_email|add_class:"form-control" }}
          </div>
          <div>
            <label for="id_contact_phone" class="form-label">Contact Phone:
              {% info_icon "Phone number where the locations site contact can be reached, preferably a mobile device." %}
            </label>
            {{ form.contact_phone|add_class:"form-control" }}
          </div>
        </div>
        <div class="col-md-4">
          <div>
            <label for="id_location_function" class="form-label">Location Function:
              {% info_icon "The primary fuction or role this facilty provides." %}
            </label>
            {{ form.location_function|add_class:"form-control" }}
          </div>
          <div>
            <label for="id_site_dial_code" class="form-label">Site Dial Code:
              {% info_icon "If a unique code/prefix is required to be dialed internally when calling this facility instead of using a public number." %}
            </label>
            {{ form.site_dial_code|add_class:"form-control" }}
          </div>
          <div>
            <label for="id_trunk_access_code" class="form-label">Trunk Access Code:
              {% info_icon "If users are required to start all calls to the PSTN with a specific digit at this location, this is the digit used." %}
            </label>
            {{ form.trunk_access_code|add_class:"form-control" }}
          </div>
          <div>
            <label for="id_trunk_access_code" class="form-label">Phone Number Suffix Digits:
              {% info_icon "The number of right justified digits from the users assigned phone number that are used in a users system extension." %}
            </label>
            {{ form.trunk_access_code|add_class:"form-control" }}
          </div>
        </div>
        <div class="col-md-4">
          <div>
            <label for="id_timezone" class="form-label">Timezone:
            </label>
            <input type="text" id="id_timezone" name="timezone" class="form-control" value="{{ form.instance.timezone }}" readonly>
          </div>
          <div>
            <label for="id_latitude" class="form-label">Latitude:
            </label>
            <input type="text" id="id_latitude" name="latitude" class="form-control" value="{{ form.instance.latitude }}" readonly>
          </div>
          <div>
            <label for="id_longitude" class="form-label">Longitude:
            </label>
            <input type="text" id="id_longitude" name="longitude" class="form-control" value="{{ form.instance.longitude }}" readonly>
          </div>
          <div>
            <label></label>
            <p></p>
            {% if form.instance.latitude and form.instance.longitude %}
              <a href="https://www.google.com/maps?q={{ form.instance.latitude }},{{ form.instance.longitude }}" target="_blank" class="btn btn-primary">View on Google Maps</a>
            {% elif form.instance.formatted_address %}
              <a href="https://www.google.com/maps/search/?api=1&query={{ form.instance.formatted_address }}" target="_blank" class="btn btn-primary">View on Google Maps</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <label for="id_notes" class="form-label">Notes:</label>
      {{ form.notes|add_class:"form-control" }}
    </div>
  </div>
</div>
{% endblock %}



{% block extra_js %}
{% endblock %}

telephony/templates/telephony/location_function.html
{% extends 'telephony/base.html' %}
{% load custom_filters %}

{% block content %}
<h2>Location Functions</h2>
{% endblock %}

{% block form_content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3">
      <label for="id_function_name" class="form-label">*Name:</label>
      {{ form.function_name|add_class:"form-control" }}
    </div>
    <div class="col-md-9">
      <label for="id_description" class="form-label">Description:</label>
      {{ form.description|add_class:"form-control" }}
    </div>
  </div>
</div>
{% endblock %}

telephony/templates/telephony/service_provider.html
{% extends 'telephony/base.html' %}
{% load custom_filters %}

{% block title %}
Service Providers
{% endblock %}

{% block content %}
<h2>Service Providers</h2>
{% endblock %}

{% block form_content %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3">
        <label for="id_provider_name" class="form-label">*Provider Name:</label>
        {{ form.provider_name|add_class:"form-control" }}
      </div>
      <div class="col-md-3">
        <label for="id_support_number" class="form-label">Support Number:</label>
        {{ form.support_number|add_class:"form-control" }}
      </div>
      <div class="col-md-3">
        <label for="id_website_url" class="form-label">Website:</label>
        {{ form.website_url|add_class:"form-control" }}
      </div>
      <div class="col-md-3">
        <label for="id_contract_number" class="form-label">Contract:</label>
        {{ form.contract_number|add_class:"form-control" }}
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <label for="id_conract_details" class="form-label">Contract Details:</label>
        {{ form.contract_details|add_class:"form-control" }}
      </div>
      <div class="col-md-6">
        <label for="id_notes" class="form-label">Notes:</label>
        {{ form.notes|add_class:"form-control" }}
      </div>
    </div>
  </div>
{% endblock %}

{% block extra_js %}
{% endblock %}